services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/var/www/html
      # - ./docker/php/nginx/default.conf:/etc/nginx/conf.d/
      - ./docker/php/nginx/snippets:/etc/nginx/snippets
    ports:
      - "80:80"
    networks:
      - whatsapp-bot-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: saas_db
      MYSQL_USER: saas_user
      MYSQL_PASSWORD: saas_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - whatsapp-bot-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - whatsapp-bot-network

networks:
  whatsapp-bot-network:
    driver: bridge

volumes:
  db_data: